# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]


permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: change directories
      run: cd /home/ubuntu/actions-runner/_work/sampleApp/sampleApp
    - name: setup envoiremnet
      run: python3 -m venv venv
    - name: activate envoiremnet
      run: source venv/bin/activate
    - name: delpoy
      run: |
         coverage run /home/ubuntu/actions-runner/_work/sampleApp/sampleApp/sample.py  &
   
 
